inputDir: "/home/esp/scriptDevelopment/multiCaveFeatures/test_pdbs"
outDir: "/home/esp/scriptDevelopment/multiCaveFeatures/features"
msmsDir: "/home/esp/bin/MSMS"
aminoAcidTable: "/home/esp/scriptDevelopment/multiCaveFeatures/amino_acid_properties.txt"